require_relative './lib/monster.rb'
require_relative './lib/hero.rb'
require_relative './lib/heros/warrior.rb'
require_relative './lib/monsters/slime.rb'
require_relative './lib/text-animations/battle-animations.rb'
require_relative './lib/battle.rb'